CREATE TABLE oc_share (
    id            BIGINT       NOT NULL AUTO_INCREMENT,
    share_type    SMALLINT     NOT NULL,
    share_with    VARCHAR(255) NULL,
    uid_owner     VARCHAR(64)  NOT NULL,
    uid_initiator VARCHAR(64)  NOT NULL,
    parent        BIGINT       NULL,
    item_type     VARCHAR(64)  NOT NULL,
    item_source   BIGINT       NOT NULL,
    file_source   BIGINT       NOT NULL,
    file_target   VARCHAR(512) NOT NULL,
    permissions   INTEGER      NOT NULL,
    stime         BIGINT       NOT NULL,
    accepted      SMALLINT     NOT NULL DEFAULT 1,
    expiration    TIMESTAMP    NULL,
    token         VARCHAR(32)  NULL,
    password      VARCHAR(255) NULL,
    mail_send     SMALLINT     NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY        idx_share_with        (share_with, share_type),
    KEY        idx_share_owner       (uid_owner),
    KEY        idx_share_item_source (item_source),
    UNIQUE KEY idx_share_token       (token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
