[application]
name = "rustcloud-ui"
default_platform = "web"

[web.app]
title = "Rustcloud"

[web.watcher]
reload_html = false
watch_path = ["src", "assets"]

[web.resource]
style = ["assets/app.css"]
script = []

[web.resource.dev]
script = []
